apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cashflow-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: cashflow.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cashflow-service
                port:
                  number: 80
